library(arrow)
library(dplyr)
library(stringr)
library(DescTools)

# read data and create column finding
lims_data <- read_parquet("/Volumes/KINGSTON/converted_parquet/MIKROBIOLOGI_Sammanstallning_Blododlingsfynd_2021_2023_LIMS.parquet") %>% mutate(finding = Mikroorganism)
wwbakt_data <- read_parquet("/Volumes/KINGSTON/converted_parquet/MIKROBIOLOGI_Sammanstallning_Blododlingsfynd_2011-2021_wwBakt.parquet") %>% mutate(finding = BaText)

# Rename bacteria -----
# Purpose: merge names from LIMS and wwLab, fix language issues
rename_bacteria <- function(df) {
  ## renaming and translating species - this takes height for all misspellings etc we have encountered in Bactius, wwLab, and LIMS
  df <- df %>%
    mutate(finding = tolower(finding), # this is just for harmonising, in the older systems, names were fully CAPITALIZED
           species = case_when(str_detect(finding, "actinomycetemcomitans") ~ "aggregatibacter actinomycetemcomitans",
                               str_detect(finding, "acinetobacter calcoaceticus-komplexet") ~ "acinetobacter calcoaceticus",
                               str_detect(finding, "dubliniensis") ~ "candida dubliniensis",
                               str_detect(finding, "acinetobacter baumannii") ~ "acinetobacter baumannii",
                               str_detect(finding, "acinetobacter-art") ~ "acinetobacter species",
                               str_detect(finding, "aeromonas hydrophila") ~ "aeromonas hydrophila",
                               str_detect(finding, "aeromonas-art") ~ "aeromonas species",
                               str_detect(finding, "anaerob blandflora") ~ "anaerobic mixed growth",
                               str_detect(finding, "anaeroba gramnegativa kocker") ~ "anaerobic gramnegative cocci",
                               str_detect(finding, "anaeroba bakterier") ~ "anaerobic bacteria",
                               str_detect(finding, "anaerob gram-negativ och gram-positiv blandflora") ~ "anaerobic gramnegative and grampositive mixed flora",
                               str_detect(finding, "anaeroba gram-negativa kocker") ~ "anaerobic gramnegative cocci",
                               str_detect(finding, "anaerob gram negativ blandflora") ~ "anaerobic gramnegative mixed growth",
                               str_detect(finding, "anaeroba gramnegativa stavar") ~ "anaerobic gramnegative rods",
                               str_detect(finding, "anaeroba gram-negativa stavar") ~ "anaerobic gramnegative rods",
                               str_detect(finding, "anaeroba grampositiva kocker") ~ "anaerobic grampositive cocci",
                               str_detect(finding, "anaeroba gram-positiva kocker") ~ "anaerobic grampositive cocci",
                               str_detect(finding, "anaerob gram positiv blandflora") ~ "anaerobic grampositive mixed growth",
                               str_detect(finding, "anaeroba grampositiva stavar") ~ "anaerobic grampositive rods",
                               str_detect(finding, "anaeroba gram-positiva stavar") ~ "anaerobic grampositive rods",
                               str_detect(finding, "anaerob växt") ~ "anaerobic growth",
                               str_detect(finding, "blandflora av anaeroba bakt.") ~ "anaerobic mixed growth",
                               str_detect(finding, "anaerob blandflora") ~ "anaerobic mixed growth",
                               str_detect(finding, "anaeroba streptokocker") ~ "anaerobic streptococci",
                               str_detect(finding, "bacillus cereus-komplexet") ~ "bacillus cereus",
                               str_detect(finding, "bacillus-art") ~ "bacillus species",
                               str_detect(finding, "bacillus") ~ "bacillus species",
                               str_detect(finding, "bacteroides tillh. b.fragilis gruppen") ~ "bacteroides fragilis",
                               str_detect(finding, "bacteroides-art") ~ "bacteroides species",
                               str_detect(finding, "brevibacterium-art") ~ "brevibacterium species",
                               str_detect(finding, "campylobacter jejuni") ~ "campylobacter jejuni",
                               str_detect(finding, "chryseobacterium-art") ~ "chryseobacterium species",
                               str_detect(finding, "citrobacter-art") ~ "citrobacter species",
                               str_detect(finding, "clostridium-art") ~ "clostridium species",
                               str_detect(finding, "corynebacterium-art") ~ "corynebacterium species",
                               str_detect(finding, "delftia-art") ~ "delftia species",
                               str_detect(finding, "desulfovibrio-art") ~ "desulfovibrio species",
                               str_detect(finding, "eggerthella-art") ~ "aegerthella species",
                               str_detect(finding, "enterobacter cloacae-komplexet") ~ "enterobacter cloacae",
                               str_detect(finding, "enterobacter-art") ~ "enterobacter species",
                               str_detect(finding, "enterococcus gallinarum-gruppen") ~ "enterococcus gallinarum",
                               str_detect(finding, "enterokock-art") ~ "enterococcus species",
                               str_detect(finding, "e.coli") ~ "escherichia coli",
                               str_detect(finding, "e.coli") ~ "escherichia coli",
                               str_detect(finding, "eubacterium-art") ~ "eubacterium species",
                               str_detect(finding, "exiguobacterium-art") ~ "exiguobacterium species",
                               str_detect(finding, "finegoldia magna") ~ "finegoldia magna",
                               str_detect(finding, "fusobacterium-art") ~ "fusobacterium species",
                               str_detect(finding, "gramnegativa kocker") ~ "gramnegative cocci",
                               str_detect(finding, "gram negativa kocker, ej artbestämda") ~ "gramnegative cocci",
                               str_detect(finding, "gramnegativ miljöbakterie") ~ "gramnegative environmental bacteria",
                               str_detect(finding, "gram negativ miljöbakterie") ~ "gramnegative environmental bacteria",
                               str_detect(finding, "gram negativ blandflora, bl.a. proteus") ~ "gramnegative mixed flora",
                               str_detect(finding, "gramnegativ blandflora") ~ "gramnegative mixed flora",
                               str_detect(finding, "gramnegativa stavar") ~ "gramnegative rods",
                               str_detect(finding, "gram-negativa stavar") ~ "gramnegative rods",
                               str_detect(finding, "gram neg stavar, ej artbestämda") ~ "gramnegative rods",
                               str_detect(finding, "gramnegativ tarmbakterie") ~ "gramnegative rods (enterobacterales)",
                               str_detect(finding, "gram-negativ stav tillhö. enterobacteriaceae") ~ "gramnegative rods (enterobacterales)",
                               str_detect(finding, "grampositiva kocker") ~ "grampositive cocci",
                               str_detect(finding, "grampositiva kocker, troligen strepto- eller enterokocker") ~ "grampositive cocci",
                               str_detect(finding, "gram-positiva kocker") ~ "grampositive cocci",
                               str_detect(finding, "gram positiv kock,ej artbestämd") ~ "grampositive cocci",
                               str_detect(finding, "grampositiva kocker, troligen stafylokocker") ~ "grampositive cocci",
                               str_detect(finding, "grampositiv blandflora") ~ "grampositive mixed flora",
                               str_detect(finding, "grampositiva stavar") ~ "grampositive rods",
                               str_detect(finding, "gram-positiva stavar") ~ "grampositive rods",
                               str_detect(finding, "gramlabila stavar") ~ "grampositive rods",
                               str_detect(finding, "haemophilus influenzae serotyp/biotyp") ~ "haemophilus influenzae",
                               str_detect(finding, "enterobacter aerogenes") ~ "klebsiella aerogenes  ",
                               str_detect(finding, "klebsiella oxytoca-gruppen") ~ "klebsiella oxytoca",
                               str_detect(finding, "klebsiella pneumoniae") ~ "klebsiella pneumoniae",
                               str_detect(finding, "klebsiella-art") ~ "klebsiella species",
                               str_detect(finding, "lactobacillus-art") ~ "lactobacillus species",
                               str_detect(finding, "leptotrichia-art") ~ "leptotrichia species  ",
                               str_detect(finding, "leuconostoc-art") ~ "leuconostoc species",
                               str_detect(finding, "listeria monocytogenes serotyp") ~ "listeria monocytogenes",
                               str_detect(finding, "mikroaerofila gram positiva kocker") ~ "microaerophilic grampositive cocci",
                               str_detect(finding, "mikroaerofila gram-positiva stavar") ~ "microaerophilic grampositive rods",
                               str_detect(finding, "mikrokock-art") ~ "micrococcus species",
                               str_detect(finding, "mikroaerofila streptokocker") ~ "microaerophilic streptococci",
                               str_detect(finding, "blandflora") ~ "mixed flora",
                               str_detect(finding, "blandflora") ~ "mixed flora",
                               str_detect(finding, "blandflora av tarmbakterier") ~ "mixed growth of enterobacterales",
                               str_detect(finding, "moraxella-art") ~ "moraxella species",
                               str_detect(finding, "mycobacterium fortuitum-komplexet") ~ "mycobacterium fortuitum",
                               str_detect(finding, "myroides species f.d flavobacterium") ~ "myroides species",
                               str_detect(finding, "neisseria meningitidis") ~ "neisseria meningitidis",
                               str_detect(finding, "neisseria-art") ~ "neisseria species",
                               str_detect(finding, "troligen neisseria") ~ "neisseria species",
                               str_detect(finding, "paenibacillus-art") ~ "pantoea species",
                               str_detect(finding, "pantoea-art") ~ "pantoea species",
                               str_detect(finding, "peptostreptococcus-art") ~ "peptostreptococcus species",
                               str_detect(finding, "porphyromonas-art") ~ "porphyromonas species",
                               str_detect(finding, "bivia") ~ "prevotella bivia",
                               str_detect(finding, "buccalis") ~ "prevotella buccalis",
                               str_detect(finding, "melaninogenica") ~ "prevotella melaninogenica",
                               str_detect(finding, "prevotella-art") ~ "prevotella species",
                               str_detect(finding, "propionibacterium-art") ~ "proprionebacterium species",
                               str_detect(finding, "proteus mirabilis") ~ "proteus mirabilis",
                               str_detect(finding, "proteus vulgaris-gruppen") ~ "proteus vulgaris",
                               str_detect(finding, "providencia-art") ~ "providencia species",
                               str_detect(finding, "pseudomonas-art") ~ "pseudomonas species",
                               str_detect(finding, "psychrobacter-art") ~ "psychrobacter species",
                               str_detect(finding, "ralstonia-art") ~ "ralstonia species",
                               str_detect(finding, "ornithinolytica") ~ "raoultella ornithinolytica",
                               str_detect(finding, "planticola") ~ "raoultella planticola",
                               str_detect(finding, "rothia-art") ~ "rothia species  ",
                               str_detect(finding, "salmonella-art") ~ "salmonella species",
                               str_detect(finding, "selenomonas-art") ~ "selenomonas species",
                               str_detect(finding, "serratia-art") ~ "serratia species",
                               str_detect(finding, "hudflora") ~ "skin flora",
                               str_detect(finding, "meticillinresistent s.aureus") ~ "staphylococcus aureus",
                               str_detect(finding, "troligen staphylococcus aureus") ~ "staphylococcus aureus",
                               str_detect(finding, "staphylococcus species, ej s.aureus") ~ "staphylococcus species",
                               str_detect(finding, "stafylokocker ?, ej s.aureus") ~ "staphylococcus species",
                               str_detect(finding, "koagulas-negativa stafylokocker") ~ "staphylococcus species",
                               str_detect(finding, "staphylococcus species") ~ "staphylococcus species",
                               str_detect(finding, "streptokocker grupp b") ~ "streptococcus agalactiae",
                               str_detect(finding, "streptokocker grupp b serotyp ii") ~ "streptococcus agalactiae",
                               str_detect(finding, "streptokocker grupp b serotyp iii") ~ "streptococcus agalactiae",
                               str_detect(finding, "streptococcus agalactiae") ~ "streptococcus agalactiae",
                               str_detect(finding, "streptococcus anginosus-komplexet") ~ "streptococcus anginosus",
                               str_detect(finding, "streptococcus anginosus-gruppen") ~ "streptococcus anginosus",
                               str_detect(finding, "streptococcus bovis-komplexet") ~ "streptococcus bovis",
                               str_detect(finding, "streptococcus bovis-gruppen") ~ "streptococcus bovis",
                               str_detect(finding, "streptococcus species tillhörande s.bovis gruppen.") ~ "streptococcus bovis",
                               str_detect(finding, "betastreptokocker grupp g") ~ "streptococcus dysgalactiae",
                               str_detect(finding, "streptococcus dysgalactiae") ~ "streptococcus dysgalactiae",
                               str_detect(finding, "betastreptokocker grupp c") ~ "streptococcus dysgalactiae",
                               str_detect(finding, "streptococcus dysgalactiae") ~ "streptococcus dysgalactiae",
                               str_detect(finding, "beta-streptokocker grupp g") ~ "streptococcus dysgalactiae",
                               str_detect(finding, "beta-streptokocker grupp c") ~ "streptococcus dysgalactiae",
                               str_detect(finding, "beta-streptokocker") ~ "streptococcus dysgalactiae",
                               str_detect(finding, "streptococcus mitis-gruppen") ~ "streptococcus mitis",
                               str_detect(finding, "streptococcus mitis-komplexet") ~ "streptococcus mitis",
                               str_detect(finding, "streptococcus mitis-oralis") ~ "streptococcus mitis",
                               str_detect(finding, "streptococcus pneumoniae") ~ "streptococcus pneumoniae",
                               str_detect(finding, "streptococcus pneumoniae typ") ~ "streptococcus pneumoniae",
                               str_detect(finding, "pneumokocker") ~ "streptococcus pneumoniae",
                               str_detect(finding, "gram-positiva kocker, prel pneumokocker") ~ "streptococcus pneumoniae",
                               str_detect(finding, "beta-streptokocker grupp a") ~ "streptococcus pyogenes",
                               str_detect(finding, "beta-streptokocker grupp a") ~ "streptococcus pyogenes",
                               str_detect(finding, "streptococcus pyogenes") ~ "streptococcus pyogenes",
                               str_detect(finding, "streptococcus salivarius-komplexet") ~ "streptococcus salivarius",
                               str_detect(finding, "streptococcus salivarius-gruppen") ~ "streptococcus salivarius",
                               str_detect(finding, "streptococcus sanguinis-komplexet") ~ "streptococcus sanguinis",
                               str_detect(finding, "alfa-streptokocker") ~ "streptococcus species",
                               str_detect(finding, "streptokock-art") ~ "streptococcus species",
                               str_detect(finding, "streptokocker av alfa-streptokock typ") ~ "streptococcus species",
                               str_detect(finding, "veillonella-art") ~ "veillonella species",
                               str_detect(finding, "jästsvamp") ~ "yeast",
                               str_detect(finding, "jästsvamp") ~ "yeast",
                               str_detect(finding, "jästsvamp, ej c.albicans") ~ "yeast",
                               str_detect(finding, "jästsvamp?") ~ "yeast",
                               str_detect(finding, "streptococcus mutans-komplexet") ~ "streptococcus mutans",
                               str_detect(finding, "maltophilia") ~ "stenotrophomonas maltophilia",
                               str_detect(finding, "sporosarcina-art") ~ "sporosarcina species",
                               str_detect(finding, "serratia liquefaciens-komplexet") ~ "serratia liquefaciens",
                               str_detect(finding, "mucilaginosus") ~ "rothia mucilaginosa",
                               str_detect(finding, "radiobacter") ~ "rhizobium radiobacter",
                               str_detect(finding, "asaccharolytica") ~ "porphyromonas asaccharolytica",
                               str_detect(finding, "agglomerans") ~ "pantoea agglomerans",
                               str_detect(finding, "morganii") ~ "morganella morganii",
                               str_detect(finding, "laktobaciller ,") ~ "lactobacillus species",
                               str_detect(finding, "laktobaciller") ~ "lactobacillus species",
                               str_detect(finding, "fusarium solani.") ~ "fusarium solani",
                               str_detect(finding, "pneumosintes") ~ "dialister pneumosintes",
                               str_detect(finding, "vesicularis") ~ "brevundimonas vesicularis",
                               str_detect(finding, "blandflora av anaeroba gram.neg. stavar") ~ "anaerobic mixed growth",
                               str_detect(finding, "acinetobacter johnsonii") ~ "acinetobacter johnsonii",
                               str_detect(finding, "alfastreptokocker") ~ "streptococcus species",
                               str_detect(finding, "bifidobacterium-art") ~ "bifidobacterium species",
                               str_detect(finding, "brachybacterium-art") ~ "brachybacterium species  ",
                               str_detect(finding, "burkholderia cepacia-komplexet") ~ "burkholderia cepacia",
                               str_detect(finding, "comamonas-art") ~ "comamonas species",
                               str_detect(finding, "difteroida stavar") ~ "difteroid rods",
                               str_detect(finding, "trådsvamp") ~ "fungus",
                               str_detect(finding, "munflora") ~ "oral flora",
                               str_detect(finding, "stafylokocker") ~ "staphylococcus species",
                               str_detect(finding, "strept. gallolyticus ssp gallolyticus") ~ "streptococcus gallolyticus",
                               str_detect(finding, "streptococcus equi subsp zooepidemicus") ~ "streptococcus equi",
                               str_detect(finding, "svamp species") ~ "fungus",
                               str_detect(finding, "troligen pneumokocker") ~ "streptococcus pneumoniae",
                               str_detect(finding, "wickerhamomyces anomalus") ~ "candida pelliculosa",
                               str_detect(finding, "clavispora lusitaniae") ~ "candida lusitaniae",
                               str_detect(finding, "kluyveromyces marxianus") ~ "candida kefyr",
                               str_detect(finding, "ingen växt") ~ "negative",
                               TRUE ~ finding),
           # this creates a classification whith is more clinically relevant but still quite granular
           genus = case_when(str_detect(species, "escherichia coli") ~ "escherichia coli",
                             str_detect(species, "staphylococcus aureus") ~ "staphylococcus aureus",
                             str_detect(species, "lugdunensis") ~ "staphylococcus lugdunensis",
                             str_detect(species, "staphylococcus") ~ "staphylococcus species",
                             str_detect(species, "bacteroides") ~ "bacteroides species",
                             str_detect(species, "klebsiella") ~ "klebsiella species",
                             str_detect(species, "streptococcus pneumoniae") ~ "streptococcus pneumoniae",
                             str_detect(species, "dysgalactiae|Betastreptokocker grupp g|agalactiae|pyogenes") ~ "beta-hemolytic streptococci",
                             str_detect(species, "enterococcus") ~ "enterococcus species",
                             str_detect(species, "pseudomonas") ~ "pseudomonas species",
                             str_detect(species, "proteus") ~ "proteus species",
                             str_detect(species, "streptococcus") ~ "alpha-hemolytic streptococci",
                             str_detect(species, "candida") ~ "candida species",
                             str_detect(species, "clostridium") ~ "clostridium species",
                             str_detect(species, "enterobacter") ~ "enterobacter species",
                             str_detect(species, "citrobacter") ~ "citrobacter species",
                             str_detect(species, "listeria") ~ "listeria species",
                             str_detect(species, "neisseria") ~ "neisseria species",
                             str_detect(species, "fusobacterium") ~ "fusobacterium species",
                             str_detect(species, "salmonella") ~ "salmonella species",
                             str_detect(species, "aerococcus") ~ "aerococcus species",
                             TRUE ~ species),
  species = StrCap(species, "first"),
  genus = StrCap(genus, "first"),
  finding = StrCap(finding, "first"))
  return(df)
}

wwbakt_data_species <- rename_bacteria(wwbakt_data) %>% select(BaText, species) %>% distinct()
lims_data_species <- rename_bacteria(lims_data) %>% select(Mikroorganism, species) %>% distinct()

# spara
write_parquet(lims_data_species, "LIMS_rename_bacteria.parquet")
write_parquet(wwbakt_data_species, "wwBakt_rename_bacteria.parquet")
